title: Open Minded Productions
description: Open Minded Productions is a fiercely DIY, wholly passionate, friend/family run, production company based in Israel
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
